Dev
CTC-Organization/API-Agenda-Saude pull request #11
Opened 2024-07-28 01:24 UTC by christiandoramo

<small>🏥 _Template para Pull Requests - Agenda Saúde_ 🚑</small>

### Preencha o que for necessário para abrir a PR

**Data e hora de publicação** <small>(_Insira a data e hora no formato DD/MM/AAAA HH:MM_)</small>

> :point_right: 27/07/2024 22:17

**Alterações principais:** <small>(_Descreva aqui as principais alterações feitas nesta PR._)</small>

> :point_right: Adição de serviços de request e attachment

**Descrição detalhada:** <small>(_Quais e como cada função/classe/módulo/arquivo foi criado/deletado/modificado_)</small>

> :point_right: todos os arquivos relativos a request e attachment

-   [x] **As alterações pertencem a algum quadro no Trello:** <small>(_Insira o quadro no formato [nome](link do quadro)_)</small>
    > :point_right: Attachment e Request
    > :link: [Attachment](https://trello.com/c/pORIy4TA/21-attachment-entity-service-controller)
-   [ ] Você seguiu os padrões e convenções de commit?  
         ❓ **Referências:**

    -   [<small>_Padrões de commit_</small>](https://github.com/iuricode/padroes-de-commits.git)
    -   [<small>_Convenções de commit_</small>](https://www.conventionalcommits.org/pt-br/v1.0.0/)
        > Sim :bulb:

-   [ ] **Foi testado?**  
        <small> Não foi testado usando testes automatizados </small>

    | Alteração     | Tipo de Teste | Número de Testes | Testes Aprovados |
    | ------------- | ------------- | ---------------- | ---------------- |
    | Alteração 1   | Unitários     | 10   | 10    |
    | Alteração 2   | Integração    | [Insira aqui]    | [Insira aqui]    |
    | Alteração 2   | Ponta a Ponta | [Insira aqui]    | [Insira aqui]    |
    | Alteração (n) | Unitários     | [Insira aqui]    | [Insira aqui]    |

-   [ ] **Precisa de testes? Se sim, o que deve ser testado e qual o critério de aceitação de cada alteração**
    > :point_right:  Testar métodos no Postman (apenas create request foi testado - nenhum metodo attachment foi testado). Critério de aceitação: programa está funcionando - correções e implementações continuam na próxima sprint

:rocket:

2024-07-28 12:53 UTC, LuizFprog requested changes
Resolver tudo que eu deixei comentado

2024-07-28 12:53 UTC, LuizFprog commented on src/repositories/attachment-prisma.repository.ts
> +    async deleteAttachmentsByRequestId(requestId: string): Promise<void> {
Remover comentários dessa função

2024-07-28 12:53 UTC, LuizFprog commented on src/repositories/attachment-prisma.repository.ts
> +    async createAttachments({ files, referenceId, attachmentType, folder }: CreateAttachmentsDto) {
Como já tem comentários explicando o código em cima da função, não há necessidade de ter comentários dentro da função

2024-07-28 12:53 UTC, LuizFprog commented on src/repositories/attachment-prisma.repository.ts
> +    async createAttachment({ file, referenceId, attachmentType, folder }: CreateAttachmentDto) {
Como já tem comentários explicando o código em cima da função, não há necessidade de ter comentários dentro da função

2024-07-28 12:53 UTC, LuizFprog commented on src/repositories/attachment-prisma.repository.ts
Resolver os três problemas achados no código

2024-07-28 12:53 UTC, LuizFprog commented on src/repositories/patient-prisma.repository.ts
Remover Comentários de createPatient

2024-07-28 12:53 UTC, LuizFprog commented on src/services/auth.service.ts
Apagar trash code em createToken

2024-07-28 12:53 UTC, LuizFprog commented on src/services/patient.service.ts
Apagar trash code linha 24, entre CreatePatientSchema e PatientService

2024-07-28 12:53 UTC, LuizFprog commented on src/services/request.service.ts
Apagar trash code abaixo dos imports

2024-07-28 12:53 UTC, LuizFprog commented on src/services/service-token.service.ts
Apagar trash code após os imports e em createServiceToken

2024-07-28 12:53 UTC, LuizFprog commented on src/tests/env-config.service.spec.ts
Apagar comentários do código

2024-07-28 12:53 UTC, LuizFprog commented on src/tests/patient.service.spec.ts
Remover todos os comentários desse código, os testes já estão autoexplicativos

2024-07-28 12:53 UTC, LuizFprog commented on src/tests/user.service.spec.ts
Remover comentários do código, testes são autoexplicativos. Também era possível ter criado o mock como uma constante como foi feito nos testes de patientService, para evitar a desorganização do código e aumentar a legibilidade

2024-07-28 12:53 UTC, LuizFprog commented on tsconfig.json
Apagar comentários

2024-07-28 12:53 UTC, LuizFprog commented on src/controllers/request.controller.ts
Comentário no lugar errado

2024-07-28 12:53 UTC, LuizFprog commented on src/dto/create-patient.dto.ts
Apagar comentário desnecessário

2024-07-28 12:53 UTC, LuizFprog commented on src/modules/patient.module.ts
Apagar comentário

2024-07-28 13:41 UTC, christiandoramo commented on src/repositories/attachment-prisma.repository.ts
> +    async deleteAttachmentsByRequestId(requestId: string): Promise<void> {
comentários removidos

2024-07-28 13:41 UTC, christiandoramo commented on src/repositories/attachment-prisma.repository.ts
> +    async createAttachments({ files, referenceId, attachmentType, folder }: CreateAttachmentsDto) {
comentários removidos

2024-07-28 13:43 UTC, christiandoramo commented
comentários removidos: 

https://github.com/CTC-Organization/API-Agenda-Saude/pull/11/commits/276d7d77f6a3e0b61e3deb8123927ec3e241a9d7#diff-fc6abb76fb0224e8601571b6cb261153530d5d279e1dbdec6773f016828750af

https://github.com/CTC-Organization/API-Agenda-Saude/pull/11/commits/51b175c76e917234da6e5fc8bfa7ba7af2c627c0#diff-de5e092efe5dc053aa62ca743062b3d0f01da2df33dce5eff0a966760cd66204

2024-07-28 15:34 UTC, christiandoramo commented
Trash codes e comentários removidos. Testes do jest aprovados

https://github.com/CTC-Organization/API-Agenda-Saude/pull/11/commits/3a1c02278bf88a0d466abeb55b1126f0487e9bea

2024-07-28 15:39 UTC, christiandoramo commented
Alterações feitas

2024-08-10 15:26 UTC, LuizFprog approved these changes

2024-08-10 15:27 UTC, merged